import Head from 'next/head'
import styles from '../styles/Home.module.css'

import VideoBroadcast from './_videobroadcast';

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>forum cache</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="./public/primary-logo-2022-(favicon).png" />
      </Head>
      <VideoBroadcast />
    </div>
  )
}
