import Head from 'next/head'
import styles from '../styles/Home.module.css'

import Header from './_header';
import Lander from './_lander';

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>forum cache</title>
        <meta name="description" content="Generated by create next app" />

        <link rel="icon" href="/logo.ico" />
        <link rel="stylesheet" href="https://use.typekit.net/hnm3zjg.css"></link>
        <link rel="stylesheet" href="https://use.typekit.net/hnm3zjg.css"></link>
      </Head>
      <Header />
      <Lander />
    </div>
  )
}
